# num_people = 10000
# size_x = 300
# size_y = 300
# speed_stdev = 10
# init_infected = 1
# init_vaccinated = 0
# infection_prob_infected_to_general = 0.1
# infection_prob_infected_to_healed = 0.02
# infection_prob_infected_to_vaccinated = 0.001
# infection_prob_vaccinated_to_general = 0.06
# infection_prob_vaccinated_to_healed = 0.0012
# infection_prob_vaccinated_to_vaccinated = 0.0006
# infection_avg_duration = 30
# death_rate = 0.02
